namespace Configastic.SharedModels.Interfaces
{
    public enum ControlPrograms : byte
    {
        NoControl = 0,
        TurnOn = 1,
        TurnOff = 2,
        TurnOnForTime = 3,
        TurnOffForTime = 4,
        Blink_OffInitialPosition = 5,
        Blink_OnInitialPosition = 6,
        BlinkForTime_OffInitialPosition = 7,
        BlinkForTime_OnInitialPosition = 8,
        Lamp = 9,
        AlarmOutput1 = 10,
        ASPT = 11,
        Siren = 12,
        FireOutput = 13,
        FaultOutput = 14,
        FireLamp = 15,
        AlarmOutput2 = 16,
        TurnOnForTimeBeforeArming = 17,
        TurnOffForTimeBeforeArming = 18,
        TurnOnForTimeUponArming = 19,
        TurnOffForTimeUponArming = 20,
        TurnOnForTimeUponDisarming = 21,
        TurnOffForTimeUponDisarming = 22,
        TurnOnForTimeIfArmingFailed = 23,
        TurnOffForTimeIfArmingFailed = 24,
        TurnOnForTimeUponAuxActivation = 25,
        TurnOffForTimeUponAuxActivation = 26,
        TurnOnUponDisarming = 27,
        TurnOffUponDisarming = 28,
        TurnOnUponArming = 29,
        TurnOffUponArming = 30,
        TurnOnUponAuxActivation = 31,
        TurnOffUponAuxActivation = 32,
        ASPT_1 = 33,
        ASPT_A = 34,
        ASPT_A1 = 35,
        TurnOnIfIncreased = 36,
        TurnOnIfDecreased = 37,
        TurnOnIfFire2 = 50,
        TurnOffIfFire2 = 51,
        BlinkForTimeIfFire2_OffInitialPosition = 52,
        BlinkForTimeIfFire2_OnInitialPosition = 53,
        TurnOnIfAttack = 54,
        TurnOffIfAttack = 55
    }
}
